- hosts: all
  tasks:
  - name: Install Git
    import_role:
      name: ansible-git-role

  - name: Clone App Repo
    git:
      repo: https://github.com/ikambarov/Flaskex
      dest: /Flaskex

  - name: Install Pip
    import_role:
      name: ansible-pip-role

  - name: Install pip requirements
    pip:
      requirements: /Flaskex/requirements.txt 

  - name: Start App
    shell: "pkill app.py; nohup python app.py &"
    args:
      chdir: /Flaskex
